### ISSUE TITLE
Supporting Subassemblies as Parts?

### ISSUE THREAD

**Issue by shederman** [magico13/ScrapYard#3]
Would there be a possible way to have subassemblies stored as parts in the inventory together? I'm thinking a gameplay where we recondition an entire rocket or stage rather than the individual parts that make it up?

You'd have to be able to:
- Identify all parts as coming from a common subassembly
- Put the parts in ScrapYard as one "Part"
- Allow "Break up for parts" for such Subassembly parts
- Possibly also allow a "Build subassembly from parts", if I want to add my Centaur Upper Stage but I want to do it efficiently.

**Comment by magico13** [comment]
This is something I had in my roadmap as a future idea to try to move the vessel storage functionality of KCT out into this mod instead. Unfortunately I'm not longer developing this mod and it has been taken over instead by @severedsolo. You can find his [fork here](https://github.com/severedsolo/ScrapYard) and I'd recommend recreating this suggestion there.
