### ISSUE TITLE
Used chutes fitted to ship are already deployed

### ISSUE THREAD

**Issue by liamdennehy** [magico13/ScrapYard#4]
Using ScrapYard it appears fitting a used parachute (tested with Mk2-R radial chute) to a ship doesn't repack before launch. This means a ship is sitting on the pad with used and already deployed chutes - drasically reducing the chance my luttle dudes don't lithobrake when coming home.

Strangely this only seems to happen when they are fitted to the command pod (Mk1-3 in my case), as the same model of chute attached to my SRBs and tanks seem fine, but is otherwise quite consistent.

While I am using KCT, these are "normal recover" parts, not KCT recovery.

ScrapYard version: 2.0.0.1
KSP version: 1.8.1 Linux x64

**Comment by liamdennehy** [comment]
Stages show lower chutes packed, upper chutes not available:
![ScrapYard-4 Showing stages](https://user-images.githubusercontent.com/4996358/97083455-89ac7280-1610-11eb-82a7-6aa60c6cec74.png)

Deploy available on lower chutes (and show they are used):
![ScrapYard-4 Showing Deploy Available on Tank](https://user-images.githubusercontent.com/4996358/97083463-a21c8d00-1610-11eb-976a-4e0df105e46e.png)

Deploy not available on pod (and also used):
![ScrapYard-4 Showing Deploy not available on pod](https://user-images.githubusercontent.com/4996358/97083516-ed36a000-1610-11eb-8d14-242b847d48b6.png)

Once in orbit, engineer can repack but on other missions the part gets only a two-star rating from users :( :
![ScrapYard-4 Showing Repack needed](https://user-images.githubusercontent.com/4996358/97083501-e019b100-1610-11eb-9ea8-a06e9c3af0dd.png)

**Comment by liamdennehy** [comment]
And..... I'm now confused. "Part is New" but already deployed???
![ScrapYard-4 Showing New Part Already Deployed](https://user-images.githubusercontent.com/4996358/97087452-a5247700-162a-11eb-9322-763305756711.png)

**Comment by magico13** [comment]
Just a heads up but I'm not the active developer/maintainer of this anymore so you'll likely want to move this to the appropriate repo. That is/was https://github.com/severedsolo/ScrapYard but I'm not 100% sure if that's still the case.

ScrapYard has a mechanism for modifying parts on recovery to do things like repack chutes so you might be able to utilize that to fix this on your end. Unfortunately I'm not sure I can provide any other advice or help at this time, it's been a long while since I did anything with KSP or this mod.

**Comment by liamdennehy** [comment]
CKAN is stating this is now https://github.com/zer0Kerbal/ScrapYard (forked from severedsolo), thanks for responding anyway. Maybe deactivate this repo to avoid being bothered in the future ;)
